### ISSUE TITLE
[BUG] Import functions

### ISSUE THREAD

**Issue by ahatdude** [angrycuban13/Scripts#9]
Hi!
I was testing this on unraid and it wasn't working.

```
# Import functions
Import-Module $PSScriptRoot\Upgradinatorr.psm1 -Force
```

When cloning the repo, the file has a lower case and it was causing me errors. Capitalizing the first letter has fixed it.

**Comment by angrycuban13** [comment]
Oh man nice catch, this is what I get for letting VSCode auto complete lol.

I've fixed it in 030a65cdc50a71f46d2e5ae919dee82b00f8b1ca
